name: Build Static Page and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './pnpm-lock.yaml'
      - name: Install  # 下载依赖 打包项目
        run: |
          npn install
          npm install pnpm -g      
          pnpm install
      - name: Build
        run:
          pnpm run build
      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # ACCESS_TOKEN 是我的 secret 名称
          BRANCH: main
          FOLDER: dist
          REPOSITORY_NAME: Andy-qinyuhai/chatgpt-page.github.io # 这是我的 github page 仓库
          TARGET_FOLDER: github-actions-page # 打包的文件将放到静态服务器 github-actions-demo 目录下
